const white = (x, y, z, sector, label) => ({ color: 0xffffff, x, y, z, sector, label });
const red = (x, y, z, sector = 'ALL_ROUND', label = 'Rotes Rundumlicht') => ({ color: 0xff0000, x, y, z, sector, label });
const green = (x, y, z, sector = 'ALL_ROUND', label = 'Grünes Rundumlicht') => ({ color: 0x00ff00, x, y, z, sector, label });

const largePowerLights = [
    white(0, 14, -4, 'MASTHEAD', 'Vorderes Topplicht'),
    white(0, 20, 12, 'MASTHEAD', 'Hinteres Topplicht'),
    red(-6, 6, -4, 'PORT', 'Backbord-Seitenlicht'),
    green(6, 6, -4, 'STARBOARD', 'Steuerbord-Seitenlicht'),
    white(0, 6, 20, 'STERN', 'Hecklicht'),
];

const smallPowerLights = [
    white(0, 5, 2, 'MASTHEAD', 'Topplicht'),
    red(-2, 1, -2, 'PORT', 'Backbord-Seitenlicht'),
    green(2, 1, -2, 'STARBOARD', 'Steuerbord-Seitenlicht'),
    white(0, 1, 6, 'STERN', 'Hecklicht'),
];

const sailingLights = [
    red(-1.7, 0.8, -2, 'PORT', 'Backbord-Seitenlicht'),
    green(1.7, 0.8, -2, 'STARBOARD', 'Steuerbord-Seitenlicht'),
    white(0, 0.8, 5, 'STERN', 'Hecklicht'),
];

const restrictedLights = [
    red(0, 24, 0),
    white(0, 19, 0, 'ALL_ROUND', 'Weißes Rundumlicht'),
    red(0, 14, 0),
    ...largePowerLights,
];

const restrictedStopped = [
    red(0, 24, 0),
    white(0, 19, 0, 'ALL_ROUND', 'Weißes Rundumlicht'),
    red(0, 14, 0),
];

const elbeWarningLights = [
    ...largePowerLights,
    red(0, 17, -4, 'ALL_ROUND', 'Zusätzliches rotes Rundumlicht (Bleib-weg-Signal)'),
];

const notUnderCommandStopped = [
    red(0, 20, 0),
    red(0, 14, 0),
];

const notUnderCommandMoving = [
    ...notUnderCommandStopped,
    red(-6, 2.5, -4, 'PORT', 'Backbord-Seitenlicht'),
    green(6, 2.5, -4, 'STARBOARD', 'Steuerbord-Seitenlicht'),
    white(0, 6, 16, 'STERN', 'Hecklicht'),
];

const answerSets = {
    restricted: ['Manövrierbehindertes Fahrzeug', 'Manövrierunfähiges Fahrzeug', 'Trawler', 'Schleppverband'],
    smallPower: ['Maschinenfahrzeug unter 50 m', 'Segelfahrzeug', 'Trawler', 'Manövrierunfähiges Fahrzeug'],
    sailing: ['Segelfahrzeug in Fahrt', 'Maschinenfahrzeug unter 50 m', 'Fischereifahrzeug', 'Schleppverband'],
};

function scenario({
    id,
    title,
    cardDesc,
    vesselType,
    lights,
    routePreset,
    question,
    answers,
    correctIndex = 0,
    explanation,
    rule,
    shipColor = 0x1a3a6e,
}) {
    return {
        id,
        sourceQuestion: { category: 'Schifffahrtsrecht', id: id.split('-').at(-1) },
        title,
        cardDesc,
        vesselType,
        lights,
        lightDots: lights.map(light => `#${light.color.toString(16).padStart(6, '0')}`),
        routePreset,
        question,
        answers,
        correctIndex,
        explanation,
        rule,
        shipColor,
    };
}

export const SCENARIOS = [
    scenario({
        id: 'schifffahrtsrecht-13',
        title: 'Wegerechtschiff',
        cardDesc: 'Tanker mit rot-weiß-rot zusätzlich zu den Fahrtlichtern',
        vesselType: 'restricted',
        lights: restrictedLights,
        routePreset: 'head_on',
        question: 'Welche Bedeutung hat die zusätzliche Lichterführung rot-weiß-rot?',
        answers: answerSets.restricted,
        explanation: 'Rot-weiß-rot kennzeichnet hier ein manövrierbehindertes Wegerechtschiff.',
        rule: 'SeeSchStrO / KVR Regel 27',
    }),
    scenario({
        id: 'schifffahrtsrecht-14',
        title: 'Manövrierbehindert ohne Fahrt',
        cardDesc: 'Rot-weiß-rot ohne zusätzliche Fahrtlichter',
        vesselType: 'restricted',
        lights: restrictedStopped,
        routePreset: 'stationary',
        question: 'Was bedeutet rot-weiß-rot senkrecht übereinander ohne weitere Fahrtlichter?',
        answers: [
            'Manövrierbehindertes Fahrzeug ohne Fahrt durchs Wasser',
            'Manövrierbehindertes Fahrzeug mit Fahrt durchs Wasser',
            'Manövrierunfähiges Fahrzeug',
            'Fahrzeug vor Anker',
        ],
        explanation: 'Ohne zusätzliche Topp-, Seiten- und Hecklichter macht das manövrierbehinderte Fahrzeug keine Fahrt durchs Wasser. Vor Anker käme zusätzlich ein Ankerlicht dazu.',
        rule: 'KVR Regel 27 (b)(i)',
    }),
    scenario({
        id: 'schifffahrtsrecht-16',
        title: 'Motorsegler bei Nacht',
        cardDesc: 'Segelboot unter Maschine – nur Lichter eines Maschinenfahrzeugs',
        vesselType: 'sailing',
        lights: smallPowerLights,
        routePreset: 'head_on',
        question: 'Ein Segelboot fährt gleichzeitig unter Maschine. Welche Lichter zeigt es bei Nacht?',
        answers: [
            'Nur die Lichter eines Maschinenfahrzeugs (Topplicht, Seitenlichter, Hecklicht)',
            'Die normalen Segellichter plus ein zusätzliches Rundumlicht',
            'Zwei rote Rundumlichter zusätzlich',
            'Rot-weiß-rot zusätzlich zu den Segellichtern',
        ],
        explanation: 'Bei Nacht gibt es kein eigenes Erkennungslicht für den Motorsegler – geführt werden ausschließlich die Lichter eines Maschinenfahrzeugs. Der Kegel mit der Spitze nach unten kennzeichnet das Fahrzeug nur bei Tage.',
        rule: 'KVR Regel 25 (e)',
        shipColor: 0x2d5a1b,
    }),
    scenario({
        id: 'schifffahrtsrecht-21',
        title: 'Treibnetzfischer',
        cardDesc: 'Nicht trawlendes Fischereifahrzeug mit Fanggerät über 150 m',
        vesselType: 'fishing',
        lights: [
            red(0, 18, 0),
            white(0, 12, 0, 'ALL_ROUND', 'Weißes Rundumlicht'),
            white(-12, 10, 0, 'ALL_ROUND', 'Licht in Richtung des Fanggeräts'),
        ],
        routePreset: 'head_on',
        question: 'Welches Fahrzeug zeigt rot über weiß und ein zusätzliches weißes Licht seitlich?',
        answers: ['Treibnetzfischer mit Fanggerät über 150 m', 'Trawler', 'Schleppverband', 'Manövrierunfähiges Fahrzeug'],
        explanation: 'Rot über weiß kennzeichnet ein fischendes Fahrzeug, das nicht trawlt. Das zusätzliche weiße Licht zeigt zum weit ausgebrachten Fanggerät.',
        rule: 'KVR Regel 26 (c)',
        shipColor: 0x5a3a1a,
    }),
    scenario({
        id: 'schifffahrtsrecht-22',
        title: 'Manövrierunfähig ohne Fahrt',
        cardDesc: 'Zwei rote Rundumlichter ohne Fahrt durchs Wasser',
        vesselType: 'not_under_command',
        lights: notUnderCommandStopped,
        routePreset: 'stationary',
        question: 'Was bedeuten zwei rote Rundumlichter senkrecht übereinander?',
        answers: ['Manövrierunfähiges Fahrzeug ohne Fahrt durchs Wasser', 'Manövrierbehindertes Fahrzeug', 'Treibnetzfischer', 'Fahrzeug vor Anker'],
        explanation: 'Zwei rote Rundumlichter kennzeichnen ein manövrierunfähiges Fahrzeug. Ohne Seiten- und Hecklicht macht es keine Fahrt durchs Wasser.',
        rule: 'KVR Regel 27 (a)',
        shipColor: 0x3a1a1a,
    }),
    scenario({
        id: 'schifffahrtsrecht-23',
        title: 'Manövrierunfähig mit Fahrt',
        cardDesc: 'Manövrierunfähiges Fahrzeug mit sichtbarem Backbordlicht',
        vesselType: 'not_under_command',
        lights: notUnderCommandMoving,
        routePreset: 'port_side',
        question: 'Was zeigt dieses Fahrzeug zusätzlich zu den zwei roten Rundumlichtern an?',
        answers: ['Es macht Fahrt durchs Wasser', 'Es liegt vor Anker', 'Es ist ein Trawler', 'Es schleppt ein Fahrzeug'],
        explanation: 'Das sichtbare Backbord-Seitenlicht zeigt, dass das manövrierunfähige Fahrzeug Fahrt durchs Wasser macht.',
        rule: 'KVR Regel 27 (a)',
        shipColor: 0x3a1a1a,
    }),
    scenario({
        id: 'schifffahrtsrecht-32',
        title: 'Gierendes Maschinenfahrzeug',
        cardDesc: 'Maschinenfahrzeug unter 50 m, nahezu von vorn',
        vesselType: 'small_power',
        lights: smallPowerLights,
        routePreset: 'gyring_head_on',
        question: 'Um welches Fahrzeug handelt es sich?',
        answers: answerSets.smallPower,
        explanation: 'Ein Topplicht und die wechselnd sichtbaren Seitenlichter kennzeichnen ein gierendes Maschinenfahrzeug unter 50 m.',
        rule: 'KVR Regeln 14 und 23',
    }),
    scenario({
        id: 'schifffahrtsrecht-38',
        title: 'Rotes Licht eines Segelfahrzeugs',
        cardDesc: 'Backbord-Seitenlicht eines Segelfahrzeugs',
        vesselType: 'sailing',
        lights: sailingLights,
        routePreset: 'port_side',
        question: 'Was ist das einzelne rote Licht?',
        answers: ['Backbordlicht eines Segelfahrzeugs', 'Rotes Rundumlicht eines Fischers', 'Hecklicht eines Maschinenfahrzeugs', 'Ankerlicht'],
        explanation: 'Aus diesem Blickwinkel ist nur das rote Backbord-Seitenlicht des Segelfahrzeugs sichtbar.',
        rule: 'KVR Regeln 12 und 25',
        shipColor: 0x2d5a1b,
    }),
    scenario({
        id: 'schifffahrtsrecht-39',
        title: 'Grünes Licht eines Segelfahrzeugs',
        cardDesc: 'Steuerbord-Seitenlicht eines Segelfahrzeugs',
        vesselType: 'sailing',
        lights: sailingLights,
        routePreset: 'starboard_side',
        question: 'Was ist das einzelne grüne Licht?',
        answers: ['Steuerbordlicht eines Segelfahrzeugs', 'Grünes Rundumlicht eines Trawlers', 'Hecklicht eines Maschinenfahrzeugs', 'Ankerlicht'],
        explanation: 'Aus diesem Blickwinkel ist nur das grüne Steuerbord-Seitenlicht des Segelfahrzeugs sichtbar.',
        rule: 'KVR Regeln 12 und 25',
        shipColor: 0x2d5a1b,
    }),
    scenario({
        id: 'schifffahrtsrecht-40',
        title: 'Gierendes Segelfahrzeug',
        cardDesc: 'Wechsel zwischen Heck- und Backbord-Seitenlicht',
        vesselType: 'sailing',
        lights: sailingLights,
        routePreset: 'gyring_stern',
        question: 'Worum handelt es sich bei den sichtbaren weißen und roten Lichtern?',
        answers: ['Heck- und Backbordlicht eines Segelfahrzeugs', 'Topp- und Backbordlicht eines Maschinenfahrzeugs', 'Fischereifahrzeug', 'Schleppverband'],
        explanation: 'Das gierende Segelfahrzeug wird nahe seiner Sektorengrenze zwischen Heck- und Backbordlicht beobachtet.',
        rule: 'KVR Regeln 13 und 25',
        shipColor: 0x2d5a1b,
    }),
    scenario({
        id: 'schifffahrtsrecht-41',
        title: 'Manövrierbehindertes Fahrzeug mit Fahrt',
        cardDesc: 'Rot-weiß-rot und Fahrtlichter',
        vesselType: 'restricted',
        lights: restrictedLights,
        routePreset: 'approaching_from_stern',
        question: 'Was bedeuten rot-weiß-rot und die zusätzlichen Fahrtlichter?',
        answers: answerSets.restricted,
        explanation: 'Rot-weiß-rot kennzeichnet ein manövrierbehindertes Fahrzeug. Topp- und Seitenlichter zeigen Fahrt durchs Wasser.',
        rule: 'KVR Regel 27 (b)',
    }),
    scenario({
        id: 'schifffahrtsrecht-48',
        title: 'Maschinenfahrzeug direkt voraus',
        cardDesc: 'Topplicht und beide Seitenlichter',
        vesselType: 'small_power',
        lights: smallPowerLights,
        routePreset: 'head_on',
        question: 'Was ist das entgegenkommende Fahrzeug?',
        answers: answerSets.smallPower,
        explanation: 'Ein Topplicht und beide Seitenlichter zeigen ein Maschinenfahrzeug unter 50 m auf nahezu entgegengesetztem Kurs.',
        rule: 'KVR Regeln 14 und 23',
    }),
    scenario({
        id: 'schifffahrtsrecht-49',
        title: 'Maschinenfahrzeug an Backbord',
        cardDesc: 'Topplicht und grünes Steuerbord-Seitenlicht',
        vesselType: 'small_power',
        lights: smallPowerLights,
        routePreset: 'starboard_side',
        question: 'Welche Seite des Maschinenfahrzeugs ist sichtbar?',
        answers: ['Steuerbord-Seite', 'Backbord-Seite', 'Heckseite', 'Keine Seite'],
        explanation: 'Das grüne Seitenlicht kennzeichnet die sichtbare Steuerbord-Seite des Maschinenfahrzeugs.',
        rule: 'KVR Regeln 15 und 23',
    }),
    scenario({
        id: 'schifffahrtsrecht-51',
        title: 'Maschinenfahrzeug an Steuerbord',
        cardDesc: 'Topplicht und rotes Backbord-Seitenlicht',
        vesselType: 'small_power',
        lights: smallPowerLights,
        routePreset: 'port_side',
        question: 'Welche Seite des Maschinenfahrzeugs ist sichtbar?',
        answers: ['Backbord-Seite', 'Steuerbord-Seite', 'Heckseite', 'Keine Seite'],
        explanation: 'Das rote Seitenlicht kennzeichnet die sichtbare Backbord-Seite des Maschinenfahrzeugs.',
        rule: 'KVR Regeln 15 und 23',
    }),
    scenario({
        id: 'schifffahrtsrecht-62',
        title: 'Bleib-weg-Signal auf der Elbe',
        cardDesc: 'Zusätzliches rotes Rundumlicht bei einem Fahrzeug mit gefährlichen Gütern',
        vesselType: 'large_power',
        lights: elbeWarningLights,
        routePreset: 'head_on',
        question: 'Sie sehen und hören auf der Elbe nachts ein Fahrzeug mit einem zusätzlichen roten Rundumlicht, das fortwährend das Schallsignal kurz-lang gibt. Was bedeutet das und wie verhalten Sie sich?',
        answers: [
            'Bleib-weg-Signal: Gefahr durch gefährliche/radioaktive Güter oder Explosionsgefahr – größten Abstand halten',
            'Signal eines manövrierbehinderten Fahrzeugs – Vorfahrt beachten',
            'Ankersignal – normale Vorbeifahrt möglich',
            'Lotsenanforderung – auf Anfrage warten',
        ],
        explanation: 'Das zusätzliche rote Rundumlicht zusammen mit dem Schallsignal kurz-lang ist das Bleib-weg-Signal. Es warnt vor austretenden gefährlichen oder radioaktiven Stoffen bzw. Explosionsgefahr. Größtmöglichen Abstand halten, keine elektrischen Schalter bedienen, kein offenes Feuer.',
        rule: 'Binnenschifffahrtsstraßen-Ordnung (Elbe) – Bleib-weg-Signal',
        shipColor: 0x5a2a18,
    }),
    scenario({
        id: 'schifffahrtsrecht-80',
        title: 'Motorsportboot schleppt Sportboot',
        cardDesc: 'Keine besondere Lichterführung trotz Schleppfahrt',
        vesselType: 'small_power',
        lights: smallPowerLights,
        routePreset: 'starboard_side',
        question: 'Ein Motorsportboot schleppt ein anderes Sportboot. Welche besondere Lichterführung muss es zeigen?',
        answers: [
            'Keine – es zeigt die normalen Lichter eines Maschinenfahrzeugs',
            'Zusätzliches gelbes Schlepplicht über dem Topplicht',
            'Zwei Topplichter senkrecht übereinander',
            'Rot-weiß-rot wie ein manövrierbehindertes Fahrzeug',
        ],
        explanation: 'Motorsportfahrzeuge, die andere Sportfahrzeuge schleppen, gelten nicht als schleppende Maschinenfahrzeuge im Sinne der KVR. Es ist daher keine besondere Lichterführung vorgeschrieben – nur die normalen Lichter eines Maschinenfahrzeugs.',
        rule: 'KVR Regel 24 (Ausnahme für Sportfahrzeuge)',
    }),
    scenario({
        id: 'schifffahrtsrecht-77',
        title: 'Bagger bei Unterwasserarbeiten',
        cardDesc: 'Manövrierbehindertes Fahrzeug mit gekennzeichneter Passierseite',
        vesselType: 'dredger',
        lights: [
            ...restrictedLights,
            green(-10, 15, 0), green(-10, 10, 0),
            red(10, 15, 0), red(10, 10, 0),
        ],
        routePreset: 'head_on',
        question: 'Um welches Fahrzeug handelt es sich und wo liegt die Passierseite?',
        answers: ['Bagger; Passierseite bei den grünen Lichtern', 'Trawler; Passierseite bei den roten Lichtern', 'Schlepper; freie Seite am Heck', 'Manövrierunfähiges Fahrzeug'],
        explanation: 'Rot-weiß-rot kennzeichnet den manövrierbehinderten Bagger. Zwei grüne Rundumlichter markieren die Passierseite, zwei rote die gesperrte Seite.',
        rule: 'KVR Regel 27 (d)',
        shipColor: 0x6a5418,
    }),
];
