export function getUI() {
    return {
        mainMenu:           document.getElementById('main-menu'),
        loadingScreen:      document.getElementById('loading-screen'),
        hud:                document.getElementById('hud'),
        hudScenarioName:    document.getElementById('hud-scenario-name'),
        btnBackHud:         document.getElementById('btn-back-hud'),        
        quizPanel:          document.getElementById('quiz-panel'),
        quizToggle:         document.getElementById('quiz-toggle'),         
        quizBody:           document.getElementById('quiz-body'),            
        quizQuestion:       document.getElementById('quiz-question'),
        answerGrid:         document.getElementById('answer-grid'),
        resultOverlay:      document.getElementById('result-overlay'),
        resultIcon:         document.getElementById('result-icon'),
        resultTitle:        document.getElementById('result-title'),
        resultExplanation:  document.getElementById('result-explanation'),
        resultRule:         document.getElementById('result-rule'),
        btnResultBack:      document.getElementById('btn-result-back'),      
        progressBarFill:    document.getElementById('progress-bar-fill'),   
        progressLabel:      document.getElementById('progress-label'),      
        creditsModal:       document.getElementById('credits-modal'),       
        shortcutsModal:     document.getElementById('shortcuts-modal'),     
        btnCredits:         document.getElementById('btn-credits'),        
        btnCreditsClose:    document.getElementById('btn-credits-close'),  
        btnShortcuts:       document.getElementById('btn-shortcuts'),      
        btnShortcutsClose:  document.getElementById('btn-shortcuts-close'),
    };
}